// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIDSS.Repository.ReturnModels
{
    public partial class AspNetUsers
    {
        public AspNetUsers()
        {
            EmployeeToInstitution = new HashSet<EmployeeToInstitution>();
        }

        public string Id { get; set; }
        public long IdfUserId { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public DateTimeOffset? LockoutEnd { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public bool? BlnDisabled { get; set; }
        public string StrDisabledReason { get; set; }
        public DateTime? DatPasswordLastChanged { get; set; }
        public bool PasswordResetRequired { get; set; }
        public string NormalizedUsername { get; set; }
        public string ConcurrencyStamp { get; set; }
        public string NormalizedEmail { get; set; }
        public DateTime? DateDisabled { get; set; }

        public virtual TstUserTable IdfUser { get; set; }
        public virtual ICollection<EmployeeToInstitution> EmployeeToInstitution { get; set; }
    }
}