// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class spUserGroupDetail_SelectDetailResult
    {
        public long idfEmployeeGroup { get; set; }
        public long? idfsEmployeeGroupName { get; set; }
        public string strGroupName { get; set; }
        public string strNationalGroupName { get; set; }
        public long idfsSite { get; set; }
        public string strSiteID { get; set; }
        public string strDescription { get; set; }
    }
}
