// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIDSS.Repository.ReturnModels
{
    /// <summary>
    /// Employee Group Members
    /// </summary>
    public partial class TlbEmployeeGroupMember
    {
        /// <summary>
        /// Group identifier
        /// </summary>
        public long IdfEmployeeGroup { get; set; }
        public long IdfEmployee { get; set; }
        public int IntRowStatus { get; set; }
        public Guid Rowguid { get; set; }
        public string StrMaintenanceFlag { get; set; }
        public string StrReservedAttribute { get; set; }
        public long? SourceSystemNameId { get; set; }
        public string SourceSystemKeyValue { get; set; }
        public string AuditCreateUser { get; set; }
        public DateTime? AuditCreateDtm { get; set; }
        public string AuditUpdateUser { get; set; }
        public DateTime? AuditUpdateDtm { get; set; }

        public virtual TlbEmployee IdfEmployeeNavigation { get; set; }
        public virtual TrtBaseReference SourceSystemName { get; set; }
    }
}