// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIDSS.Repository.ReturnModels
{
    /// <summary>
    /// Employees
    /// </summary>
    public partial class TlbEmployee
    {
        public TlbEmployee()
        {
            TlbEmployeeGroupMember = new HashSet<TlbEmployeeGroupMember>();
            TstObjectAccess = new HashSet<TstObjectAccess>();
        }

        /// <summary>
        /// Employee/group identifier
        /// </summary>
        public long IdfEmployee { get; set; }
        /// <summary>
        /// Employee/group type identifier
        /// </summary>
        public long IdfsEmployeeType { get; set; }
        /// <summary>
        /// Site identifier
        /// </summary>
        public long IdfsSite { get; set; }
        public int IntRowStatus { get; set; }
        public Guid Rowguid { get; set; }
        public string StrMaintenanceFlag { get; set; }
        public string StrReservedAttribute { get; set; }
        public long? SourceSystemNameId { get; set; }
        public string SourceSystemKeyValue { get; set; }
        public string AuditCreateUser { get; set; }
        public DateTime? AuditCreateDtm { get; set; }
        public string AuditUpdateUser { get; set; }
        public DateTime? AuditUpdateDtm { get; set; }
        public long IdfsEmployeeCategory { get; set; }

        public virtual TrtBaseReference IdfsEmployeeCategoryNavigation { get; set; }
        public virtual TrtBaseReference IdfsEmployeeTypeNavigation { get; set; }
        public virtual TrtBaseReference SourceSystemName { get; set; }
        public virtual TlbPerson TlbPerson { get; set; }
        public virtual ICollection<TlbEmployeeGroupMember> TlbEmployeeGroupMember { get; set; }
        public virtual ICollection<TstObjectAccess> TstObjectAccess { get; set; }
    }
}