// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIDSS.Repository.ReturnModels
{
    /// <summary>
    /// Offices
    /// </summary>
    public partial class TlbOffice
    {
        public TlbOffice()
        {
            EmployeeToInstitution = new HashSet<EmployeeToInstitution>();
            TlbPerson = new HashSet<TlbPerson>();
        }

        /// <summary>
        /// Office identifier
        /// </summary>
        public long IdfOffice { get; set; }
        /// <summary>
        /// Office name identifier
        /// </summary>
        public long? IdfsOfficeName { get; set; }
        /// <summary>
        /// Office abbreviation identifier
        /// </summary>
        public long? IdfsOfficeAbbreviation { get; set; }
        /// <summary>
        /// Country identifier
        /// </summary>
        public long IdfCustomizationPackage { get; set; }
        public long? IdfLocation { get; set; }
        /// <summary>
        /// Site identifier
        /// </summary>
        public long? IdfsSite { get; set; }
        /// <summary>
        /// Office Contact phone number
        /// </summary>
        public string StrContactPhone { get; set; }
        public int IntRowStatus { get; set; }
        public Guid Rowguid { get; set; }
        public int? IntHacode { get; set; }
        public string StrOrganizationId { get; set; }
        public string StrMaintenanceFlag { get; set; }
        public string StrReservedAttribute { get; set; }
        public long? OrganizationTypeId { get; set; }
        public long? OwnershipFormId { get; set; }
        public long? LegalFormId { get; set; }
        public long? MainFormOfActivityId { get; set; }
        public long? SourceSystemNameId { get; set; }
        public string SourceSystemKeyValue { get; set; }
        public string AuditCreateUser { get; set; }
        public DateTime? AuditCreateDtm { get; set; }
        public string AuditUpdateUser { get; set; }
        public DateTime? AuditUpdateDtm { get; set; }

        public virtual TrtBaseReference IdfsOfficeAbbreviationNavigation { get; set; }
        public virtual TrtBaseReference IdfsOfficeNameNavigation { get; set; }
        public virtual TrtBaseReference LegalForm { get; set; }
        public virtual TrtBaseReference MainFormOfActivity { get; set; }
        public virtual TrtBaseReference OrganizationType { get; set; }
        public virtual TrtBaseReference OwnershipForm { get; set; }
        public virtual TrtBaseReference SourceSystemName { get; set; }
        public virtual ICollection<EmployeeToInstitution> EmployeeToInstitution { get; set; }
        public virtual ICollection<TlbPerson> TlbPerson { get; set; }
    }
}