// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIDSS.Repository.ReturnModels
{
    /// <summary>
    /// Base reference translated values
    /// </summary>
    public partial class TrtStringNameTranslation
    {
        /// <summary>
        /// Base reference value identifier
        /// </summary>
        public long IdfsBaseReference { get; set; }
        /// <summary>
        /// Language identifier
        /// </summary>
        public long IdfsLanguage { get; set; }
        /// <summary>
        /// Translated value in specified language 
        /// </summary>
        public string StrTextString { get; set; }
        public int IntRowStatus { get; set; }
        public Guid Rowguid { get; set; }
        public string StrMaintenanceFlag { get; set; }
        public string StrReservedAttribute { get; set; }
        public long? SourceSystemNameId { get; set; }
        public string SourceSystemKeyValue { get; set; }
        public string AuditCreateUser { get; set; }
        public DateTime? AuditCreateDtm { get; set; }
        public string AuditUpdateUser { get; set; }
        public DateTime? AuditUpdateDtm { get; set; }

        public virtual TrtBaseReference IdfsBaseReferenceNavigation { get; set; }
        public virtual TrtBaseReference IdfsLanguageNavigation { get; set; }
        public virtual TrtBaseReference SourceSystemName { get; set; }
    }
}