// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EIDSS.Repository.ReturnModels
{
    public partial class TrtVectorType
    {
        public long IdfsVectorType { get; set; }
        public string StrCode { get; set; }
        public bool BitCollectionByPool { get; set; }
        public int IntRowStatus { get; set; }
        public Guid Rowguid { get; set; }
        public string StrMaintenanceFlag { get; set; }
        public string StrReservedAttribute { get; set; }
        public long? SourceSystemNameId { get; set; }
        public string SourceSystemKeyValue { get; set; }
        public string AuditCreateUser { get; set; }
        public DateTime? AuditCreateDtm { get; set; }
        public string AuditUpdateUser { get; set; }
        public DateTime? AuditUpdateDtm { get; set; }

        public virtual TrtBaseReference IdfsVectorTypeNavigation { get; set; }
        public virtual TrtBaseReference SourceSystemName { get; set; }
    }
}