// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_Admin_UserGoupAndUser_GetListResult
    {
        public int? TotalRowCount { get; set; }
        public long? id { get; set; }
        public long? idfsEmployeeType { get; set; }
        public string Name { get; set; }
        public string TypeName { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
