// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_AGG_CASE_SETResult
    {
        public int? ReturnCode { get; set; }
        public string ReturnMessage { get; set; }
        public long? idfAggrCase { get; set; }
        public long? idfVersion { get; set; }
        public string strCaseID { get; set; }
    }
}
