// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class usp_Employee_ValidateResult
    {
        [Column("Table Name")]
        public string TableName { get; set; }
        public string RootObjectName { get; set; }
        [Column("Constraint Name")]
        public string ConstraintName { get; set; }
        public string Where { get; set; }
        public string ID { get; set; }
        public string RootTableName { get; set; }
        public string RootID { get; set; }
        public string StrRootId { get; set; }
        public string InvalidFieldName { get; set; }
        public string InvalidFieldValue { get; set; }
        public string Query { get; set; }
    }
}
