// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_ACCESS_RULE_GETListResult
    {
        public long AccessRuleID { get; set; }
        public string AccessRuleName { get; set; }
        public bool DefaultRuleIndicator { get; set; }
        public bool BorderingAreaRuleIndicator { get; set; }
        public bool ReciprocalRuleIndicator { get; set; }
        public string GrantingActorName { get; set; }
        public string GrantingSiteAdministrativeLevel1Name { get; set; }
        public string GrantingSiteAdministrativeLevel2Name { get; set; }
        public int? RecordCount { get; set; }
        public int? TotalRowCount { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
