// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_AS_CAMPAIGN_SETResult
    {
        public int? ReturnCode { get; set; }
        public string ReturnMessage { get; set; }
        public long? idfCampaign { get; set; }
        public string strCampaignID { get; set; }
    }
}
