// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_HUM_DISEASE_CONTACTS_GetListResult
    {
        public long idfContactedCasePerson { get; set; }
        public long idfHumanCase { get; set; }
        public long idfHuman { get; set; }
        public long? idfRootHuman { get; set; }
        public string strContactPersonFullName { get; set; }
        public long idfsPersonContactType { get; set; }
        public string strPersonContactType { get; set; }
        public DateTime? datDateOfLastContact { get; set; }
        public string strPlaceInfo { get; set; }
        public string strComments { get; set; }
        public string strFirstName { get; set; }
        public string strSecondName { get; set; }
        public string strLastName { get; set; }
        public DateTime? datDateofBirth { get; set; }
        public long? idfsHumanGender { get; set; }
        public long? idfCitizenship { get; set; }
        public string strContactPhone { get; set; }
        public long? idfContactPhoneType { get; set; }
        public long? idfsCountry { get; set; }
        public long? idfsRegion { get; set; }
        public long? idfsRayon { get; set; }
        public long? idfsSettlement { get; set; }
        public string strStreetName { get; set; }
        public string strPostCode { get; set; }
        public string strBuilding { get; set; }
        public string strHouse { get; set; }
        public string strApartment { get; set; }
        public bool? blnForeignAddress { get; set; }
        public string strPatientInformation { get; set; }
        public string strPatientAddressString { get; set; }
        public byte? bitIsRootMain { get; set; }
        public Guid rowguid { get; set; }
        public long? AddressID { get; set; }
    }
}
