// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_AVR_UserPermissionsGetResult
    {
        public long idfEmployee { get; set; }
        public long idfUserID { get; set; }
        public long idfsSite { get; set; }
        public string strFirstName { get; set; }
        public string strFamilyName { get; set; }
        public string GroupName { get; set; }
        public string ObjectType { get; set; }
        public long idfObjectOperation { get; set; }
        public string ObjectOperation { get; set; }
    }
}
