// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_VAS_MONITORING_SESSION_SPECIES_TO_SAMPLE_TYPE_GETListResult
    {
        public long MonitoringSessionToSampleTypeID { get; set; }
        public long MonitoringSessionID { get; set; }
        public long? SpeciesTypeID { get; set; }
        public int? AvianOrLivestock { get; set; }
        public string SpeciesTypeName { get; set; }
        public long? SampleTypeID { get; set; }
        public string SampleTypeName { get; set; }
        public int OrderNumber { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? SampleCollectedCount { get; set; }
        public long? CampaignToSampleTypeUID { get; set; }
        public int RowStatus { get; set; }
        public string RowAction { get; set; }
    }
}
