// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_CONF_ADMIN_SanitaryMatrixReportGet_GETResult
    {
        public int? intNumRow { get; set; }
        public long idfAggrSanitaryActionMTX { get; set; }
        public long idfsSanitaryAction { get; set; }
        public string strSanitaryAction { get; set; }
        public string strActionCode { get; set; }
    }
}
