// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_CONF_GetVetDiseaseList_GETResult
    {
        public long idfsBaseReference { get; set; }
        public string strDefault { get; set; }
        public string name { get; set; }
        public string strIDC10 { get; set; }
        public string strOIECode { get; set; }
        public int? intHACode { get; set; }
    }
}
