// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_CONF_AGEGROUPSTATISTICALAGEGROUPMATRIX_GETLISTResult
    {
        public int? TotalRowCount { get; set; }
        public long? idfDiagnosisAgeGroupToStatisticalAgeGroup { get; set; }
        public long? idfsDiagnosisAgeGroup { get; set; }
        public string strDiagnosisAgeGroupName { get; set; }
        public long? idfsStatisticalAgeGroup { get; set; }
        public string strStatisticalAgeGroupName { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
