// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_GBL_USER_GETListResult
    {
        public long idfPerson { get; set; }
        public long idfUserID { get; set; }
        public string strFirstName { get; set; }
        public string strSecondName { get; set; }
        public string strFamilyName { get; set; }
        public long? idfInstitution { get; set; }
        public long idfsSite { get; set; }
        public int? TotalRowCount { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
