// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_BASEREF_GETListResult
    {
        public long idfsBaseReference { get; set; }
        public long idfsReferenceType { get; set; }
        public string strBaseReferenceCode { get; set; }
        public string strDefault { get; set; }
        public int? intHACode { get; set; }
        public int? intOrder { get; set; }
        public bool? blnSystem { get; set; }
        public int intRowStatus { get; set; }
        public Guid rowguid { get; set; }
        public string strMaintenanceFlag { get; set; }
        public string strReservedAttribute { get; set; }
    }
}
