// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_REF_ReportDiagnosisGroup_GETListResult
    {
        public int? TotalRowCount { get; set; }
        public long? idfsReportDiagnosisGroup { get; set; }
        public long? idfsReferenceType { get; set; }
        public string strDefault { get; set; }
        public string strName { get; set; }
        public string strCode { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
