// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_GBL_LKUP_SITE_FROM_ORGResult
    {
        public long idfsSite { get; set; }
        public string strSiteName { get; set; }
        public string strSiteID { get; set; }
    }
}
