// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_LAB_BATCH_ADVANCED_SEARCH_GETListResult
    {
        public long BatchTestID { get; set; }
        public int FavoriteIndicator { get; set; }
        public string EIDSSBatchTestID { get; set; }
        public long? BatchStatusTypeID { get; set; }
        public string BatchStatusTypeName { get; set; }
        public long? BatchTestPerformedByOrganizationID { get; set; }
        public long? BatchTestPerformedByPersonID { get; set; }
        public long? BatchTestTestNameTypeID { get; set; }
        public string BatchTestTestNameTypeName { get; set; }
        public long TestID { get; set; }
        public long? TestNameTypeID { get; set; }
        public long? TestCategoryTypeID { get; set; }
        public long? TestResultTypeID { get; set; }
        public long TestStatusTypeID { get; set; }
        public long DiseaseID { get; set; }
        public string DiseaseName { get; set; }
        public long SampleID { get; set; }
        public long? SentToOrganizationID { get; set; }
        public int? TestNumber { get; set; }
        public string Note { get; set; }
        public DateTime? StartedDate { get; set; }
        public DateTime? ResultDate { get; set; }
        public long? TestedByOrganizationID { get; set; }
        public long? TestedByPersonID { get; set; }
        public long? ResultEnteredByOrganizationID { get; set; }
        public long? ResultEnteredByPersonID { get; set; }
        public long? ValidatedByOrganizationID { get; set; }
        public long? ValidatedByPersonID { get; set; }
        public bool ReadOnlyIndicator { get; set; }
        public bool NonLaboratoryTestIndicator { get; set; }
        public bool? ExternalTestIndicator { get; set; }
        public long? PerformedByOrganizationID { get; set; }
        public DateTime? ReceivedDate { get; set; }
        public string ContactPersonName { get; set; }
        public string EIDSSReportOrSessionID { get; set; }
        public string PatientOrFarmOwnerName { get; set; }
        public string SampleTypeName { get; set; }
        public string EIDSSLaboratorySampleID { get; set; }
        public string TestNameTypeName { get; set; }
        public string TestStatusTypeName { get; set; }
        public string TestResultTypeName { get; set; }
        public string TestCategoryTypeName { get; set; }
        public DateTime? AccessionDate { get; set; }
        public string FunctionalAreaName { get; set; }
        public long? SampleStatusTypeID { get; set; }
        public string AccessionConditionOrSampleStatusTypeName { get; set; }
        public string AccessionComment { get; set; }
        public string EIDSSAnimalID { get; set; }
        public string TestRequested { get; set; }
        public long ObservationID { get; set; }
        public long? PerformedByPersonID { get; set; }
        public DateTime? PerformedDate { get; set; }
        public DateTime? ValidationDate { get; set; }
        public long SiteID { get; set; }
        public int RowStatus { get; set; }
        public bool? ReadPermissionindicator { get; set; }
        public bool? AccessToPersonalDataPermissionIndicator { get; set; }
        public bool? AccessToGenderAndAgeDataPermissionIndicator { get; set; }
        public bool? WritePermissionIndicator { get; set; }
        public bool? DeletePermissionIndicator { get; set; }
        public int RowAction { get; set; }
        public int RowSelectionIndicator { get; set; }
        public int? TotalRowCount { get; set; }
        public int? InProgressCount { get; set; }
        public int TestsCount { get; set; }
    }
}
