// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_LAB_TAB_COUNTS_GETListResult
    {
        public int? SamplesTabCount { get; set; }
        public int? TestingTabCount { get; set; }
        public int? TransferredTabCount { get; set; }
        public int? MyFavoritesTabCount { get; set; }
        public int? BatchesTabCount { get; set; }
        public int? ApprovalsTabCount { get; set; }
    }
}
