// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ILI_Aggregate_Detail_GetListResult
    {
        public int? TotalRowCount { get; set; }
        public long? idfAggregateDetail { get; set; }
        public long? idfAggregateHeader { get; set; }
        public long? idfHospital { get; set; }
        public string HospitalName { get; set; }
        public int? intAge0_4 { get; set; }
        public int? intAge5_14 { get; set; }
        public int? intAge15_29 { get; set; }
        public int? intAge30_64 { get; set; }
        public int? intAge65 { get; set; }
        public int? inTotalILI { get; set; }
        public int? intTotalAdmissions { get; set; }
        public int? intILISamples { get; set; }
        public string RowAction { get; set; }
        public int? RowStatus { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
