// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_VCTS_VECT_GetSampleTypeResult
    {
        public long idfsSampleType { get; set; }
        public string idfsstrSampleType { get; set; }
    }
}
