// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_HUM_TESTS_GetListResult
    {
        public long? idfHumanCase { get; set; }
        public long idfMaterial { get; set; }
        public string strBarcode { get; set; }
        public string strFieldBarcode { get; set; }
        public long idfsSampleType { get; set; }
        public string strSampleTypeName { get; set; }
        public DateTime? datFieldCollectionDate { get; set; }
        public long? idfSendToOffice { get; set; }
        public long? idfFieldCollectedByOffice { get; set; }
        public DateTime? datFieldSentDate { get; set; }
        public long? idfsSampleStatus { get; set; }
        public string SampleStatusTypeName { get; set; }
        public long? idfFieldCollectedByPerson { get; set; }
        public DateTime? datSampleStatusDate { get; set; }
        public Guid sampleGuid { get; set; }
        public long idfTesting { get; set; }
        public long? idfsTestName { get; set; }
        public long? idfsTestCategory { get; set; }
        public string strTestCategory { get; set; }
        public long? idfsTestResult { get; set; }
        public long idfsTestStatus { get; set; }
        public long idfsDiagnosis { get; set; }
        public string strDiagnosis { get; set; }
        public string strTestStatus { get; set; }
        public string strTestResult { get; set; }
        public string name { get; set; }
        public DateTime? datReceivedDate { get; set; }
        public DateTime? datConcludedDate { get; set; }
        public long? idfTestedByPerson { get; set; }
        public long? idfTestedByOffice { get; set; }
        public DateTime? datInterpretedDate { get; set; }
        public long? idfsInterpretedStatus { get; set; }
        public string strInterpretedStatus { get; set; }
        public string strInterpretedComment { get; set; }
        public string strInterpretedBy { get; set; }
        public DateTime? datValidationDate { get; set; }
        public bool blnValidateStatus { get; set; }
        public string strValidateComment { get; set; }
        public string strValidatedBy { get; set; }
        public Guid testGuid { get; set; }
        public int intRowStatus { get; set; }
        public string strTestedByPerson { get; set; }
        public string strTestedByOffice { get; set; }
        public bool blnNonLaboratoryTest { get; set; }
        public long? idfInterpretedByPerson { get; set; }
        public long? idfValidatedByPerson { get; set; }
        public long? idfTestValidation { get; set; }
    }
}
