// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_xSiteDocumentListGetResult
    {
        public long? EIDSSMenuId { get; set; }
        public Guid? xSiteGUID { get; set; }
        public string LanguageCode { get; set; }
        public string PageLink { get; set; }
    }
}
