// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_EMPLOYEEGROUP_BYUSER_GetDetailResult
    {
        public long idfEmployeeGroup { get; set; }
        public long? idfsEmployeeGroupName { get; set; }
        public string strName { get; set; }
    }
}
