// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_REP_VET_DateFieldSource_GETResult
    {
        public int intDateFieldSource { get; set; }
        public string strDateFieldSource { get; set; }
    }
}
