// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_VET_FARM_DELResult
    {
        public int? ReturnCode { get; set; }
        public string ReturnMessage { get; set; }
        public int? MonitoringSessionCount { get; set; }
        public int? DiseaseReportCount { get; set; }
        public int? LaboratorySampleTestResultCount { get; set; }
    }
}
