// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_FF_ParameterTypeEditorMapping_GetListResult
    {
        public long? idfsBaseReference { get; set; }
        public string idfsEditor { get; set; }
        public string Editor { get; set; }
    }
}
