// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_EMPLOYEEGROUP_DASHBOARD_GETLISTResult
    {
        public long idfsBaseReference { get; set; }
        public string strBaseReferenceCode { get; set; }
        public string strDefault { get; set; }
        public string strName { get; set; }
        public string PageLink { get; set; }
    }
}
