// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_SITE_ACTOR_GETListResult
    {
        public long ActorID { get; set; }
        public long ActorTypeID { get; set; }
        public string ActorTypeName { get; set; }
        public string ActorName { get; set; }
        public long SiteID { get; set; }
        public bool ExternalActorIndicator { get; set; }
        public bool DefaultEmployeeGroupIndicator { get; set; }
        public int RowAction { get; set; }
        public int? RowCount { get; set; }
        public int? TotalRowCount { get; set; }
        public int? CurrentPage { get; set; }
        public int? TotalPages { get; set; }
    }
}
