// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_LAB_TEST_AMENDMENT_GETListResult
    {
        public long AmendmentHistoryID { get; set; }
        public string AmendedByOrganizationName { get; set; }
        public string AmendedByPersonName { get; set; }
        public DateTime AmendmentDate { get; set; }
        public string OriginalTestResultTypeName { get; set; }
        public string ChangedTestResultTypeName { get; set; }
        public string ReasonForAmendment { get; set; }
        public int? RowCount { get; set; }
        public int? TotalRowCount { get; set; }
        public int? CurrentPage { get; set; }
        public int? TotalPages { get; set; }
    }
}
