// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_GBL_Resource_GETListResult
    {
        public long ResourceID { get; set; }
        public long LanguageID { get; set; }
        public string CultureName { get; set; }
        public string ResourceKey { get; set; }
        public string ResourceValue { get; set; }
        public bool? ResourceIsHidden { get; set; }
        public bool? ResourceIsRequired { get; set; }
    }
}
