// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_GBL_GIS_LocationAncestry_GETListResult
    {
        public long? idfsLocation { get; set; }
        public long? AdminLevel1ID { get; set; }
        public long? AdminLevel2ID { get; set; }
        public long? AdminLevel3ID { get; set; }
        public long? AdminLevel4ID { get; set; }
        public long? AdminLevel5ID { get; set; }
        public long? AdminLevel6ID { get; set; }
        public long? AdminLevel7ID { get; set; }
        public string AdminLevel1Name { get; set; }
        public string AdminLevel2Name { get; set; }
        public string AdminLevel3Name { get; set; }
        public string AdminLevel4Name { get; set; }
        public string AdminLevel5Name { get; set; }
        public string AdminLevel6Name { get; set; }
        public string AdminLevel7Name { get; set; }
        public int? Level { get; set; }
        public string LevelType { get; set; }
    }
}
