// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_FF_ParameterTypes_FILTERResult
    {
        public int? TotalRowCount { get; set; }
        public long? idfsParameterType { get; set; }
        public string DefaultName { get; set; }
        public string NationalName { get; set; }
        public long? idfsReferenceType { get; set; }
        public string BaseReferenceListName { get; set; }
        public string System { get; set; }
        public string ParameterTypeName { get; set; }
        public string LangID { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
