// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_LAB_SAMPLE_ID_GETListResult
    {
        public long SampleID { get; set; }
        public string EIDSSLaboratorySampleID { get; set; }
        public bool? ProcessedIndicator { get; set; }
    }
}
