// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_SYSTEMFUNCTION_USERPERMISSION_GetListResult
    {
        public long? IdfEmployee { get; set; }
        public long SystemFunctionID { get; set; }
        public string StrSystemFunction { get; set; }
        public long SystemFunctionOperationID { get; set; }
        public string StrSystemFunctionOperation { get; set; }
        public int? OperationStatus { get; set; }
        public int AccessStatus { get; set; }
    }
}
