// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_CONF_GetInvestigationTypes_GETResult
    {
        public long idfsBaseReference { get; set; }
        public string strDefault { get; set; }
        public string strName { get; set; }
        public int? intOrder { get; set; }
    }
}
