// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_VET_FARM_INVENTORY_GETListResult
    {
        public int RecordID { get; set; }
        public string RecordType { get; set; }
        public long? FarmID { get; set; }
        public long? FarmMasterID { get; set; }
        public long? FlockOrHerdID { get; set; }
        public long? FlockOrHerdMasterID { get; set; }
        public long? SpeciesID { get; set; }
        public long? SpeciesMasterID { get; set; }
        public long? SpeciesTypeID { get; set; }
        public string SpeciesTypeName { get; set; }
        public string EIDSSFarmID { get; set; }
        public string EIDSSFlockOrHerdID { get; set; }
        public DateTime? StartOfSignsDate { get; set; }
        public string AverageAge { get; set; }
        public int? SickAnimalQuantity { get; set; }
        public int? TotalAnimalQuantity { get; set; }
        public int? DeadAnimalQuantity { get; set; }
        public long? ObservationID { get; set; }
        public string Note { get; set; }
        public long? OutbreakCaseStatusTypeID { get; set; }
        public int? RowStatus { get; set; }
        public int? RowAction { get; set; }
        public int? TotalRowCount { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
    }
}
