// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_Country_GetLookupResult
    {
        public long idfsCountry { get; set; }
        public string strCountryName { get; set; }
        public string strCountryExtendedName { get; set; }
        public string strCountryCode { get; set; }
        public int intRowStatus { get; set; }
    }
}
