// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_GBL_DISEASE_MTX_GET_BY_UsingTypeResult
    {
        public long idfsBaseReference { get; set; }
        public string strDefault { get; set; }
        public string strIDC10 { get; set; }
    }
}
