// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_VCTS_FIELDTEST_GetListResult
    {
        public long TestID { get; set; }
        public string EIDSSLocalOrFieldSampleID { get; set; }
        public long? SampleID { get; set; }
        public long? SampleTypeID { get; set; }
        public string SampleTypeName { get; set; }
        public long? TestNameTypeID { get; set; }
        public string TestNameTypeName { get; set; }
        public long? TestCategoryTypeID { get; set; }
        public string TestCategoryTypeName { get; set; }
        public long? TestedByOrganizationID { get; set; }
        public string TestedByOrganizationName { get; set; }
        public long? TestResultTypeID { get; set; }
        public string TestResultTypeName { get; set; }
        public long? TestedByPersonID { get; set; }
        public string TestedByPersonName { get; set; }
        public long DiseaseID { get; set; }
        public string DiseaseName { get; set; }
        public string RecordAction { get; set; }
        public DateTime? ConcludedDate { get; set; }
        public DateTime? ReceivedDate { get; set; }
        public DateTime? CollectionDate { get; set; }
        public long? VectorID { get; set; }
        public int RowStatus { get; set; }
        public bool NonLaboratoryTestIndicator { get; set; }
        public bool? ExternalTestIndicator { get; set; }
        public int? TotalRowCount { get; set; }
    }
}
