// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_UserListGetForUtilityResult
    {
        public long? RowNum { get; set; }
        public int? TotalCount { get; set; }
        public long? idfPerson { get; set; }
        public string strAccountName { get; set; }
        public string strFirstName { get; set; }
        public string strFamilyName { get; set; }
        public string strSecondName { get; set; }
        public string Institution { get; set; }
        public string Site { get; set; }
        public long? idfUserID { get; set; }
        public long? idfInstitution { get; set; }
        public long? idfsSite { get; set; }
        public bool? DuplicateUserName { get; set; }
        public bool? Converted { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
