// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_OMM_Session_Parameters_GetListResult
    {
        public long OutbreakSpeciesParameterUID { get; set; }
        public long idfOutbreak { get; set; }
        public long? OutbreakSpeciesTypeID { get; set; }
        public int? CaseMonitoringDuration { get; set; }
        public int? CaseMonitoringFrequency { get; set; }
        public int? ContactTracingDuration { get; set; }
        public int? ContactTracingFrequency { get; set; }
        public int intRowStatus { get; set; }
        public long? CaseQuestionaireTemplateID { get; set; }
        public long? CaseMonitoringTemplateID { get; set; }
        public long? ContactTracingTemplateID { get; set; }
    }
}
