// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_HAS_MONITORING_SESSION_ACTION_GETListResult
    {
        public long? ROWNUM { get; set; }
        public int? TotalRowCount { get; set; }
        public long? MonitoringSessionActionID { get; set; }
        public long? MonitoringSessionID { get; set; }
        public long? EnteredByPersonID { get; set; }
        public string EnteredByPersonName { get; set; }
        public long? MonitoringSessionActionTypeID { get; set; }
        public string MonitoringSessionActionTypeName { get; set; }
        public long? MonitoringSessionActionStatusTypeID { get; set; }
        public string MonitoringSessionActionStatusTypeName { get; set; }
        public DateTime? ActionDate { get; set; }
        public string Comments { get; set; }
        public int? RowStatus { get; set; }
        public string RowAction { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
