// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_OMM_Case_GetDetailResult
    {
        public long CaseId { get; set; }
        public long? OutbreakId { get; set; }
        public long? CaseTypeId { get; set; }
        public string EIDSSCaseId { get; set; }
        public bool? PrimaryCaseIndicator { get; set; }
        public long? ClassificationTypeId { get; set; }
        public long? StatusTypeId { get; set; }
        public long? HumanDiseaseReportId { get; set; }
        public long? VeterinaryDiseaseReportId { get; set; }
        public string FarmName { get; set; }
        public long? CaseQuestionnaireObservationId { get; set; }
        public int? CaseQuestionnaireObservationFormTypeId { get; set; }
        public long? CaseEPIObservationID { get; set; }
        public int? CaseEPIObservationFormTypeId { get; set; }
        public DateTime DateEntered { get; set; }
        public DateTime? DateLastUpdated { get; set; }
        public long? CaseQuestionnaireTemplateId { get; set; }
    }
}
