// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_HUM_DISEASE_AdvanceSearch_REPORT_GETListResult
    {
        public int? TotalRowCount { get; set; }
        public long? HumanDiseaseReportID { get; set; }
        public string Report_ID { get; set; }
        public long? PatientID { get; set; }
        public long? HumanMasterID { get; set; }
        public string LegacyCaseId { get; set; }
        public string Persons_Name { get; set; }
        public DateTime? Date_Entered { get; set; }
        public string Disease { get; set; }
        public string Report_Status { get; set; }
        public string Location { get; set; }
        public string Case_Classification { get; set; }
        public string Person_ID { get; set; }
        public string Entered_By_Name { get; set; }
        public string Entered_By_Organization { get; set; }
        public string Report_Type { get; set; }
        public string Hospitalization { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
