// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_FF_ParameterSelectList_GETResult
    {
        public long? idfsParameter { get; set; }
        public long? idfsParameterType { get; set; }
        public long? idfsReferenceType { get; set; }
        public long? idfsValue { get; set; }
        public string strValueCaption { get; set; }
        public string langid { get; set; }
        public int? intOrder { get; set; }
        public int? intHACode { get; set; }
        public int? intRowStatus { get; set; }
    }
}
