// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class usp_SettlementType_GetLookupResult
    {
        public long idfsReference { get; set; }
        public string name { get; set; }
        public string strDefault { get; set; }
        public int? intOrder { get; set; }
        public int intRowStatus { get; set; }
    }
}
