// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_OMM_Case_SetResult
    {
        public int? ReturnCode { get; set; }
        public string ReturnMessage { get; set; }
        public string strOutbreakCaseId { get; set; }
        public long? OutbreakCaseReportUID { get; set; }
    }
}
