// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_SYSTEM_PREFERENCE_GETDetailResult
    {
        public long SystemPreferenceID { get; set; }
        public string PreferenceDetail { get; set; }
    }
}
