// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_GISDATA_DELResult
    {
        public int? ReturnCode { get; set; }
        public string ReturnMessage { get; set; }
        public long? IdfsLocation { get; set; }
        public int? SettlementCount { get; set; }
        public int? RayonCount { get; set; }
        public int? RegionCount { get; set; }
        public int? GeoLocationRefCount { get; set; }
        public int? GeoLocationSharedRefCount { get; set; }
    }
}
