// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_GBL_LKUP_DISEASE_GETListResult
    {
        public long DiseaseID { get; set; }
        public int? intHACode { get; set; }
        public string DiseaseName { get; set; }
        public string IDC10 { get; set; }
        public string OIECode { get; set; }
        public int? intOrder { get; set; }
        public long? UsingType { get; set; }
    }
}
