// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_GBL_SITE_GROUP_GETDetailResult
    {
        public long SiteGroupID { get; set; }
        public long? SiteGroupTypeID { get; set; }
        public string SiteGroupTypeName { get; set; }
        public long? CentralSiteID { get; set; }
        public string CentralSiteName { get; set; }
        public string CentralEIDSSSiteID { get; set; }
        public string SiteGroupName { get; set; }
        public long? CountryID { get; set; }
        public long? AdministrativeLevel1ID { get; set; }
        public string AdministrativeLevel1Name { get; set; }
        public long? AdministrativeLevel2ID { get; set; }
        public string AdministrativeLevel2Name { get; set; }
        public int? AdministrativeLevel3ID { get; set; }
        public int? AdministrativeLevel3Name { get; set; }
        public long? SettlementID { get; set; }
        public string SettlementName { get; set; }
        public string SiteGroupDescription { get; set; }
        public string ActiveStatusIndicator { get; set; }
        public int RowStatus { get; set; }
    }
}
