// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_OMM_Herd_GetListResult
    {
        public long idfHerdActual { get; set; }
        public string strHerdCode { get; set; }
        public int intRowStatus { get; set; }
        public int? intTotalAnimalQty { get; set; }
        public int? intDeadAnimalQty { get; set; }
        public int? intSickAnimalQty { get; set; }
    }
}
