// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_REF_MEASURELIST_GETListResult
    {
        public long idfsReferenceType { get; set; }
        public string strReferenceTypeName { get; set; }
        public int intStandard { get; set; }
        public long? idfsCurrentReferenceType { get; set; }
    }
}
