// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_HAS_DetailedInformation_GetListResult
    {
        public int? TotalRowCount { get; set; }
        public long? ID { get; set; }
        public long? HumanMasterID { get; set; }
        public long? PersonID { get; set; }
        public string EIDSSPersonID { get; set; }
        public string PersonName { get; set; }
        public string PersonAddress { get; set; }
        public string FieldSampleID { get; set; }
        public string DiseaseID { get; set; }
        public string Disease { get; set; }
        public long? idfsSampleType { get; set; }
        public string SampleType { get; set; }
        public DateTime? CollectionDate { get; set; }
        public long? idfSendToOffice { get; set; }
        public string SentToOrganization { get; set; }
        public string Comment { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
