// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_CONF_LKUP_DISEASE_GENDER_MATRIXResult
    {
        public long? GenderID { get; set; }
    }
}
