// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_DAS_MYCOLLECTIONS_GETListResult
    {
        public int? TotalRowCount { get; set; }
        public long? VectorSurveillanceSessionID { get; set; }
        public string SessionID { get; set; }
        public DateTime? DateEntered { get; set; }
        public string Vectors { get; set; }
        public string DiseaseName { get; set; }
        public DateTime? DateStarted { get; set; }
        public string Region { get; set; }
        public string Rayon { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
