// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_GBL_LKUP_DISEASE_GETList_PagedResult
    {
        public int? TotalRowCount { get; set; }
        public long? idfsBaseReference { get; set; }
        public string strName { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
