// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_ACCESS_RULE_ACTOR_GETListResult
    {
        public long AccessRuleActorID { get; set; }
        public long? AccessRuleID { get; set; }
        public long ActorTypeID { get; set; }
        public string ActorTypeName { get; set; }
        public string ActorName { get; set; }
        public long? ActorSiteGroupID { get; set; }
        public string SiteGroupName { get; set; }
        public long? ActorSiteID { get; set; }
        public string SiteName { get; set; }
        public long? ActorEmployeeGroupID { get; set; }
        public string EmployeeGroupName { get; set; }
        public long? ActorUserID { get; set; }
        public string UserName { get; set; }
        public bool AccessToGenderAndAgeDataPermissionIndicator { get; set; }
        public bool AccessToPersonalDataPermissionIndicator { get; set; }
        public bool CreatePermissionIndicator { get; set; }
        public bool DeletePermissionIndicator { get; set; }
        public bool ReadPermissionIndicator { get; set; }
        public bool WritePermissionIndicator { get; set; }
        public int RowStatus { get; set; }
        public bool ExternalActorIndicator { get; set; }
        public int RowAction { get; set; }
        public int? RowCount { get; set; }
        public int? TotalRowCount { get; set; }
        public int? CurrentPage { get; set; }
        public int? TotalPages { get; set; }
    }
}
