// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_VCTS_SAMPLE_GetListResult
    {
        public long? VectorID { get; set; }
        public long VectorTypeID { get; set; }
        public long VectorSubTypeID { get; set; }
        public long SampleID { get; set; }
        public long? RootSampleID { get; set; }
        public string EIDSSLaboratorySampleID { get; set; }
        public string EIDSSLocalOrFieldSampleID { get; set; }
        public long SampleTypeID { get; set; }
        public string SampleTypeName { get; set; }
        public DateTime? FieldCollectionDate { get; set; }
        public long? SentToOrganizationID { get; set; }
        public string SentToOrganizationName { get; set; }
        public long? CollectedByOrganizationID { get; set; }
        public string CollectedByOrganizationName { get; set; }
        public DateTime? SentDate { get; set; }
        public DateTime? EnteredDate { get; set; }
        public string Comments { get; set; }
        public DateTime? AccessionDate { get; set; }
        public long? AccessionConditionTypeID { get; set; }
        public string AccessionConditionTypeName { get; set; }
        public string AccessionComment { get; set; }
        public long? CaseID { get; set; }
        public long? VectorSessionKey { get; set; }
        public string VectorTypeName { get; set; }
        public string VectorSubTypeName { get; set; }
        public int Quantity { get; set; }
        public DateTime CollectionDate { get; set; }
        public string SessionID { get; set; }
        public long SiteID { get; set; }
        public long? CurrentSiteID { get; set; }
        public int AccessionedIndicator { get; set; }
        public string RecordAction { get; set; }
        public long? DiseaseID { get; set; }
        public string TestDiseaseName { get; set; }
        public int? TotalRowCount { get; set; }
    }
}
