// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_REF_AGEGROUP_GETListResult
    {
        public int? TotalRowCount { get; set; }
        public long? idfsAgeGroup { get; set; }
        public string strDefault { get; set; }
        public string strName { get; set; }
        public int? intOrder { get; set; }
        public int? intLowerBoundary { get; set; }
        public int? intUpperBoundary { get; set; }
        public long? idfsAgeType { get; set; }
        public string AgeTypeName { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
