// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_GBL_STREET_GETListResult
    {
        public long StreetID { get; set; }
        public string StreetName { get; set; }
        public long? idfsLocation { get; set; }
        public int RowStatus { get; set; }
    }
}
