// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_HUMAN_DISEASELABTESTMATRIX_BY_DISEASE_GETLISTResult
    {
        public long idfTestForDisease { get; set; }
        public long idfsDiagnosis { get; set; }
        public string strDisease { get; set; }
        public long? idfsTestName { get; set; }
        public string strTestName { get; set; }
        public long? idfsTestCategory { get; set; }
        public string strTestCategory { get; set; }
        public long? idfsSampleType { get; set; }
        public string strSampleType { get; set; }
    }
}
