// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_CONF_VECTORTYPEFIELDTESTMATRIX_GETLISTResult
    {
        public int? TotalRowCount { get; set; }
        public long? idfPensideTestTypeForVectorType { get; set; }
        public long? idfsVectorType { get; set; }
        public string strVectorTypeName { get; set; }
        public string idfsPensideTestName { get; set; }
        public string strPensideTestName { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
