// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_EMPLOYEE_GETLISTResult
    {
        public int? TotalRowCount { get; set; }
        public long EmployeeID { get; set; }
        public string FirstOrGivenName { get; set; }
        public string SecondName { get; set; }
        public string LastOrSurName { get; set; }
        public string EmployeeFullName { get; set; }
        public string ContactPhone { get; set; }
        public string OrganizationAbbreviatedName { get; set; }
        public string OrganizationFullName { get; set; }
        public string EIDSSOrganizationID { get; set; }
        public long? OrganizationID { get; set; }
        public string PositionTypeName { get; set; }
        public long? PositionTypeID { get; set; }
        public long? EmployeeCategoryID { get; set; }
        public string EmployeeCategory { get; set; }
        public string AccountDisabled { get; set; }
        public string AccountLocked { get; set; }
        public long? PersonalIdType { get; set; }
        public string PersonalIdValue { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
