// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_REF_LKUP_BASE_REFERENCE_GETListResult
    {
        public int? TotalRowCount { get; set; }
        public long? KeyId { get; set; }
        public long? idfsBaseReference { get; set; }
        public long? idfsReferenceType { get; set; }
        public string strDefault { get; set; }
        public string strName { get; set; }
        public int? intHACode { get; set; }
        public string strHACode { get; set; }
        public string strHACodeNames { get; set; }
        public int? intOrder { get; set; }
        public string LOINC { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
