// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_REF_SearchDuplicates_GetListResult
    {
        public long idfsBaseReference { get; set; }
        public long idfsReferenceType { get; set; }
        public string strDefault { get; set; }
        public string AlphaOnly { get; set; }
    }
}
