// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_SecurityConfiguration_GetResult
    {
        public int SecurityPolicyConfigurationUID { get; set; }
        public int? MinPasswordLength { get; set; }
        public int? EnforcePasswordHistoryCount { get; set; }
        public int? MinPasswordAgeDays { get; set; }
        public bool? ForceUppercaseFlag { get; set; }
        public bool? ForceLowercaseFlag { get; set; }
        public bool? ForceNumberUsageFlag { get; set; }
        public bool? ForceSpecialCharactersFlag { get; set; }
        public bool? AllowUseOfSpaceFlag { get; set; }
        public bool? PreventSequentialCharacterFlag { get; set; }
        public bool? PreventUsernameUsageFlag { get; set; }
        public int? LockoutThld { get; set; }
        public int? LockoutDurationMinutes { get; set; }
        public int? MaxSessionLength { get; set; }
        public int? SesnIdleTimeoutWarnThldMins { get; set; }
        public int? SesnIdleCloseoutThldMins { get; set; }
        public int? SesnInactivityTimeOutMins { get; set; }
        public int intRowStatus { get; set; }
        public Guid rowguid { get; set; }
        public string AuditCreateUser { get; set; }
        public DateTime AuditCreateDTM { get; set; }
        public string AuditUpdateUser { get; set; }
        public DateTime? AuditUpdateDTM { get; set; }
        public long? SourceSystemNameID { get; set; }
        public string SourceSystemKeyValue { get; set; }
    }
}
