// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_REF_LKUP_CASECLASSIFICATIONResult
    {
        public long idfsCaseClassification { get; set; }
        public string strDefault { get; set; }
        public string strName { get; set; }
        public int intOrder { get; set; }
        public bool blnInitialHumanCaseClassification { get; set; }
        public bool blnFinalHumanCaseClassification { get; set; }
        public int? intHACode { get; set; }
        public string strHACode { get; set; }
        public string strHACodeNames { get; set; }
    }
}
