// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_REF_STATISTICDATATYPE_GETListResult
    {
        public int? TotalRowCount { get; set; }
        public long? idfsStatisticDataType { get; set; }
        public long? idfsReferenceType { get; set; }
        public string strParameterType { get; set; }
        public string strdefault { get; set; }
        public string strName { get; set; }
        public bool? blnStatisticalAgeGroup { get; set; }
        public long? idfsStatisticPeriodType { get; set; }
        public string strStatisticPeriodType { get; set; }
        public long? idfsStatisticAreaType { get; set; }
        public string strStatisticalAreaType { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
