// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_GBL_SITE_GROUP_GETListResult
    {
        public long SiteGroupID { get; set; }
        public string SiteGroupTypeName { get; set; }
        public string SiteGroupName { get; set; }
        public string AdministrativeLevelName { get; set; }
        public string SiteGroupDescription { get; set; }
        public int? RowCount { get; set; }
        public int? TotalRowCount { get; set; }
        public int? CurrentPage { get; set; }
        public int? TotalPages { get; set; }
    }
}
