// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_CONF_REPORTDISEASEGROUPDISEASEMATRIX_GETLISTResult
    {
        public int? TotalRowCount { get; set; }
        public long? idfDiagnosisToGroupForReportType { get; set; }
        public string strDiagnosis { get; set; }
        public string strUsingType { get; set; }
        public string strAccessoryCode { get; set; }
        public string strIsDelete { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
