// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_FF_RuleParameterForAction_GETResult
    {
        public long idfParameterForAction { get; set; }
        public long idfsRule { get; set; }
        public long? idfsRuleAction { get; set; }
        public long idfsParameter { get; set; }
        public long idfsFormTemplate { get; set; }
    }
}
