// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_IE_DownloadTemplate_GETListResult
    {
        public long SetId { get; set; }
        public string SectionName { get; set; }
        public long ModuleId { get; set; }
        public string ModuleName { get; set; }
        public long ResourceId { get; set; }
        public string ResourceDefaultName { get; set; }
        public long? ResourceTypeId { get; set; }
        public string ResourceType { get; set; }
    }
}
