// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_CONF_CUSTOMREPORT_GETLISTResult
    {
        public int? TotalRowCount { get; set; }
        public long? idfReportRows { get; set; }
        public long? idfsCustomReportType { get; set; }
        public string strCustomReportType { get; set; }
        public long? idfsDiagnosisOrDiagnosisGroup { get; set; }
        public string strDiagnosisOrDiagnosisGroupName { get; set; }
        public string strDiseaseOrReportDiseaseGroup { get; set; }
        public long? idfsUsingType { get; set; }
        public string strUsingType { get; set; }
        public long? idfsReportAdditionalText { get; set; }
        public string strAdditionalReportText { get; set; }
        public long? idfsICDReportAdditionalText { get; set; }
        public string strICDReportAdditionalText { get; set; }
        public int? intRowOrder { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
