// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_FF_TemplatesByParameter_GETResult
    {
        public long idfsFormTemplate { get; set; }
        public long? idfsFormType { get; set; }
        public bool blnUNI { get; set; }
        public Guid rowguid { get; set; }
        public int intRowStatus { get; set; }
        public string strNote { get; set; }
        public string DefaultName { get; set; }
        public string NationalName { get; set; }
        public string NationalLongName { get; set; }
        public long? idfsEditMode { get; set; }
    }
}
