// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_DEDUPLICATION_HUMAN_DISEASE_Report_SETResult
    {
        public int? ReturnCode { get; set; }
        public string ReturnMessage { get; set; }
        public long? SurvivorDiseaseReportID { get; set; }
        public string strHumanCaseID { get; set; }
        public long? idfHuman { get; set; }
    }
}
