// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_GBL_LKUP_SAMPLESFORDISEASESResult
    {
        public long? idfsSampleType { get; set; }
        public string strSampleType { get; set; }
    }
}
