// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_HAS_CAMPAIGN_GETDetailResult
    {
        public long CampaignID { get; set; }
        public long? CampaignTypeID { get; set; }
        public string CampaignTypeName { get; set; }
        public long? CampaignStatusTypeID { get; set; }
        public string CampaignStatusTypeName { get; set; }
        public long DiseaseID { get; set; }
        public string DiseaseName { get; set; }
        public long? SampleTypeID { get; set; }
        public string SampleTypeName { get; set; }
        public DateTime? CampaignStartDate { get; set; }
        public DateTime? CampaignEndDate { get; set; }
        public string EIDSSCampaignID { get; set; }
        public string CampaignName { get; set; }
        public string CampaignAdministrator { get; set; }
        public string Conclusion { get; set; }
        public long SiteId { get; set; }
    }
}
