// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_CONF_HumanAggregateCaseMatrixVersionDiseaseList_GETResult
    {
        public long idfAggrHumanCaseMTX { get; set; }
        public long idfVersion { get; set; }
        public long idfsDiagnosis { get; set; }
        public int? intNumRow { get; set; }
        public int intRowStatus { get; set; }
        public Guid rowguid { get; set; }
        public string strMaintenanceFlag { get; set; }
        public string strReservedAttribute { get; set; }
        public long? SourceSystemNameID { get; set; }
        public string SourceSystemKeyValue { get; set; }
    }
}
