// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_ADMIN_ADMINLEVEL_GETLISTResult
    {
        public int? TotalRowCount { get; set; }
        public long? idfsCountry { get; set; }
        public string strCountryHASC { get; set; }
        public string strCountryCode { get; set; }
        public string strNationalCountryName { get; set; }
        public string strDefaultCountryName { get; set; }
        public long? idfsRegion { get; set; }
        public string strRegionHASC { get; set; }
        public string strRegionCode { get; set; }
        public string strNationalRegionName { get; set; }
        public string strDefaultRegionName { get; set; }
        public long? idfsRayon { get; set; }
        public string strRayonHASC { get; set; }
        public string strRayonCode { get; set; }
        public string strNationalRayonName { get; set; }
        public string strDefaultRayonName { get; set; }
        public string idfsSettlement { get; set; }
        public string strSettlementHASC { get; set; }
        public string strSettlementCode { get; set; }
        public string strNationalSettlementName { get; set; }
        public string strDefaultSettlementName { get; set; }
        public long? idfsSettlementType { get; set; }
        public string strSettlementTypeDefaultName { get; set; }
        public string strSettlementTypeNationalName { get; set; }
        public double? Latitude { get; set; }
        public double? Longitude { get; set; }
        public double? Elevation { get; set; }
        public int? TotalPages { get; set; }
        public int? CurrentPage { get; set; }
    }
}
