// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EIDSS.Repository.ReturnModels
{
    public partial class USP_REP_HUM_TuberculosisDiagnosisSelectLookupResult
    {
        public long idfsReference { get; set; }
        public string strName { get; set; }
        public int? intOrder { get; set; }
    }
}
