/*
Deployment script for EIDSS7_GG_ARCHIVE_MOA

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
PRINT N'Creating Function [dbo].[fn1100SearchQuery__54477830000000]...';


GO


CREATE FUNCTION [dbo].[fn1100SearchQuery__54477830000000]
(
@LangID	as nvarchar(50),
@UserID as bigint
)
returns table
as
return
select		
v.[sflHASC_SampleType_ID], 
			[ref_sflHASC_SampleType].[name] as [sflHASC_SampleType], 
			v.[sflHASC_CampaignType_ID], 
			[ref_sflHASC_CampaignType].[name] as [sflHASC_CampaignType], 
			v.[sflHASC_CampaignStatus_ID], 
			[ref_sflHASC_CampaignStatus].[name] as [sflHASC_CampaignStatus], 
			v.[sflHASC_CampaignStartDate], 
			v.[sflHASC_CampaignName], 
			v.[sflHASC_CampaignID], 
			v.[sflHASC_CampaignEndDate], 
			v.[sflHASC_CampaignAdministrator] 
from		vw1100SearchQuery__54477830000000 v

left join	fnReferenceRepair(@LangID, 19000087) [ref_sflHASC_SampleType] 
on			[ref_sflHASC_SampleType].idfsReference = v.[sflHASC_SampleType_ID] 
left join	fnReferenceRepair(@LangID, 19000116) [ref_sflHASC_CampaignType] 
on			[ref_sflHASC_CampaignType].idfsReference = v.[sflHASC_CampaignType_ID] 
left join	fnReferenceRepair(@LangID, 19000115) [ref_sflHASC_CampaignStatus] 
on			[ref_sflHASC_CampaignStatus].idfsReference = v.[sflHASC_CampaignStatus_ID] 



--Not needed--left join	fnReference(@LangID, 19000044) ref_None	-- Information String
--Not needed--on			ref_None.idfsReference = 0		-- Workaround. We dont need (none) anymore
GO
PRINT N'Creating Function [dbo].[fn1100SearchQuery__54699090000000]...';


GO


CREATE FUNCTION [dbo].[fn1100SearchQuery__54699090000000]
(
@LangID	as nvarchar(50),
@UserID as bigint
)
returns table
as
return
select		
v.[sflHASC_SampleType_ID], 
			[ref_sflHASC_SampleType].[name] as [sflHASC_SampleType], 
			v.[sflHASC_CampaignType_ID], 
			[ref_sflHASC_CampaignType].[name] as [sflHASC_CampaignType], 
			v.[sflHASC_CampaignStatus_ID], 
			[ref_sflHASC_CampaignStatus].[name] as [sflHASC_CampaignStatus], 
			v.[sflHASC_CampaignStartDate], 
			v.[sflHASC_CampaignName], 
			v.[sflHASC_CampaignID], 
			v.[sflHASC_CampaignEndDate], 
			v.[sflHASC_CampaignAdministrator] 
from		vw1100SearchQuery__54699090000000 v

left join	fnReferenceRepair(@LangID, 19000087) [ref_sflHASC_SampleType] 
on			[ref_sflHASC_SampleType].idfsReference = v.[sflHASC_SampleType_ID] 
left join	fnReferenceRepair(@LangID, 19000116) [ref_sflHASC_CampaignType] 
on			[ref_sflHASC_CampaignType].idfsReference = v.[sflHASC_CampaignType_ID] 
left join	fnReferenceRepair(@LangID, 19000115) [ref_sflHASC_CampaignStatus] 
on			[ref_sflHASC_CampaignStatus].idfsReference = v.[sflHASC_CampaignStatus_ID] 



--Not needed--left join	fnReference(@LangID, 19000044) ref_None	-- Information String
--Not needed--on			ref_None.idfsReference = 0		-- Workaround. We dont need (none) anymore
GO
PRINT N'Creating Procedure [dbo].[spGetNextNumberPrefixes]...';


GO

CREATE   PROCEDURE [dbo].[spGetNextNumberPrefixes]
AS

	
SELECT  
	nn.idfsNumberName,
	nn.strPrefix
FROM 
	dbo.tstNextNumbers nn
GO
PRINT N'Creating Procedure [dbo].[spOutbreakTypeSelectLookup]...';


GO

-- Create stored procedure spOutbreakTypeSelectLookup for OutbreakType
--##REMARKS Author: Edgard Torres
--##REMARKS Create date: 02/08/2022

--##RETURNS Don't use 

/*
--Example of a call of procedure:

exec spOutbreakTypeSelectLookup 'en'

*/ 
 
CREATE   PROCEDURE [dbo].[spOutbreakTypeSelectLookup]
	@LangID			as varchar(36)
AS
BEGIN
	select distinct
		r.idfsReference, 
		r.[name],
		r.intOrder  
		from		fnReferenceRepair(@LangID, 19000513) r
		where		r.idfsReference in
					(	
						10513001,	-- Human
						10513002,	-- Veterinary
						10513003	-- Zoonotic
					)
		order by	r.intOrder, r.[name], r.idfsReference

END
GO
PRINT N'Update complete.';


GO
