/*
Deployment script for EIDSS7_GG

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO

/*
The column idfsSite on table [dbo].[tstAggrSetting] must be changed from NULL to NOT NULL. If the table contains data, the ALTER script may not work. To avoid this issue, you must add values to this column for all rows or mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

--IF EXISTS (select top 1 1 from [dbo].[tstAggrSetting])
--    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

--GO

UPDATE  tstAggrSetting 
SET     idfsSite = 1100 
WHERE   idfsSite IS NULL
GO

PRINT N'Dropping Trigger [dbo].[TR_tstAggrSetting_I_Delete]...';


GO
DROP TRIGGER [dbo].[TR_tstAggrSetting_I_Delete];


GO
PRINT N'Dropping Default Constraint [dbo].[newid__2026]...';


GO
ALTER TABLE [dbo].[tstAggrSetting] DROP CONSTRAINT [newid__2026];


GO
PRINT N'Dropping Default Constraint [dbo].[DF_tstAggrSetting_CreateDTM]...';


GO
ALTER TABLE [dbo].[tstAggrSetting] DROP CONSTRAINT [DF_tstAggrSetting_CreateDTM];


GO
PRINT N'Dropping Default Constraint [dbo].[Def_0_2023]...';


GO
ALTER TABLE [dbo].[tstAggrSetting] DROP CONSTRAINT [Def_0_2023];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tstAggrSetting_tstSite_idfsSite]...';


GO
ALTER TABLE [dbo].[tstAggrSetting] DROP CONSTRAINT [FK_tstAggrSetting_tstSite_idfsSite];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tstAggrSetting_trtBaseReference__idfsAggrCaseType_R_941]...';


GO
ALTER TABLE [dbo].[tstAggrSetting] DROP CONSTRAINT [FK_tstAggrSetting_trtBaseReference__idfsAggrCaseType_R_941];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tstAggrSetting_trtBaseReference__idfsStatisticAreaType_R_1612]...';


GO
ALTER TABLE [dbo].[tstAggrSetting] DROP CONSTRAINT [FK_tstAggrSetting_trtBaseReference__idfsStatisticAreaType_R_1612];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tstAggrSetting_trtBaseReference__idfsStatisticPeriodType_R_1613]...';


GO
ALTER TABLE [dbo].[tstAggrSetting] DROP CONSTRAINT [FK_tstAggrSetting_trtBaseReference__idfsStatisticPeriodType_R_1613];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tstAggrSetting_trtBaseReference_SourceSystemNameID]...';


GO
ALTER TABLE [dbo].[tstAggrSetting] DROP CONSTRAINT [FK_tstAggrSetting_trtBaseReference_SourceSystemNameID];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_tstAggrSetting_tstCustomizationPackage__idfCustomizationPackage]...';


GO
ALTER TABLE [dbo].[tstAggrSetting] DROP CONSTRAINT [FK_tstAggrSetting_tstCustomizationPackage__idfCustomizationPackage];


GO

PRINT N'Starting rebuilding table [dbo].[tstAggrSetting]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tstAggrSetting] (
    [idfsAggrCaseType]        BIGINT           NOT NULL,
    [idfCustomizationPackage] BIGINT           NOT NULL,
    [idfsStatisticAreaType]   BIGINT           NOT NULL,
    [idfsStatisticPeriodType] BIGINT           NOT NULL,
    [strValue]                NVARCHAR (200)   NULL,
    [intRowStatus]            INT              CONSTRAINT [Def_0_2023] DEFAULT ((0)) NOT NULL,
    [rowguid]                 UNIQUEIDENTIFIER CONSTRAINT [newid__2026] DEFAULT (newid()) ROWGUIDCOL NOT NULL,
    [SourceSystemNameID]      BIGINT           NULL,
    [SourceSystemKeyValue]    NVARCHAR (MAX)   NULL,
    [AuditCreateUser]         NVARCHAR (200)   NULL,
    [AuditCreateDTM]          DATETIME         CONSTRAINT [DF_tstAggrSetting_CreateDTM] DEFAULT (getdate()) NULL,
    [AuditUpdateUser]         NVARCHAR (200)   NULL,
    [AuditUpdateDTM]          DATETIME         NULL,
    [idfsSite]                BIGINT           NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_XPKtstAggrSetting1] PRIMARY KEY CLUSTERED ([idfsAggrCaseType] ASC, [idfCustomizationPackage] ASC, [idfsSite] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tstAggrSetting])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tstAggrSetting] ([idfsAggrCaseType], [idfCustomizationPackage], [idfsSite], [idfsStatisticAreaType], [idfsStatisticPeriodType], [strValue], [intRowStatus], [rowguid], [SourceSystemNameID], [SourceSystemKeyValue], [AuditCreateUser], [AuditCreateDTM], [AuditUpdateUser], [AuditUpdateDTM])
        SELECT   [idfsAggrCaseType],
                 [idfCustomizationPackage],
                 [idfsSite],
                 [idfsStatisticAreaType],
                 [idfsStatisticPeriodType],
                 [strValue],
                 [intRowStatus],
                 [rowguid],
                 [SourceSystemNameID],
                 [SourceSystemKeyValue],
                 [AuditCreateUser],
                 [AuditCreateDTM],
                 [AuditUpdateUser],
                 [AuditUpdateDTM]
        FROM     [dbo].[tstAggrSetting]
        ORDER BY [idfsAggrCaseType] ASC, [idfCustomizationPackage] ASC, [idfsSite] ASC;
    END

DROP TABLE [dbo].[tstAggrSetting];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tstAggrSetting]', N'tstAggrSetting';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_XPKtstAggrSetting1]', N'XPKtstAggrSetting', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating Foreign Key [dbo].[FK_tstAggrSetting_tstSite_idfsSite]...';


GO
ALTER TABLE [dbo].[tstAggrSetting] WITH NOCHECK
    ADD CONSTRAINT [FK_tstAggrSetting_tstSite_idfsSite] FOREIGN KEY ([idfsSite]) REFERENCES [dbo].[tstSite] ([idfsSite]) NOT FOR REPLICATION;


GO
PRINT N'Creating Foreign Key [dbo].[FK_tstAggrSetting_trtBaseReference__idfsAggrCaseType_R_941]...';


GO
ALTER TABLE [dbo].[tstAggrSetting] WITH NOCHECK
    ADD CONSTRAINT [FK_tstAggrSetting_trtBaseReference__idfsAggrCaseType_R_941] FOREIGN KEY ([idfsAggrCaseType]) REFERENCES [dbo].[trtBaseReference] ([idfsBaseReference]) NOT FOR REPLICATION;


GO
PRINT N'Creating Foreign Key [dbo].[FK_tstAggrSetting_trtBaseReference__idfsStatisticAreaType_R_1612]...';


GO
ALTER TABLE [dbo].[tstAggrSetting] WITH NOCHECK
    ADD CONSTRAINT [FK_tstAggrSetting_trtBaseReference__idfsStatisticAreaType_R_1612] FOREIGN KEY ([idfsStatisticAreaType]) REFERENCES [dbo].[trtBaseReference] ([idfsBaseReference]) NOT FOR REPLICATION;


GO
PRINT N'Creating Foreign Key [dbo].[FK_tstAggrSetting_trtBaseReference__idfsStatisticPeriodType_R_1613]...';


GO
ALTER TABLE [dbo].[tstAggrSetting] WITH NOCHECK
    ADD CONSTRAINT [FK_tstAggrSetting_trtBaseReference__idfsStatisticPeriodType_R_1613] FOREIGN KEY ([idfsStatisticPeriodType]) REFERENCES [dbo].[trtBaseReference] ([idfsBaseReference]) NOT FOR REPLICATION;


GO
PRINT N'Creating Foreign Key [dbo].[FK_tstAggrSetting_trtBaseReference_SourceSystemNameID]...';


GO
ALTER TABLE [dbo].[tstAggrSetting] WITH NOCHECK
    ADD CONSTRAINT [FK_tstAggrSetting_trtBaseReference_SourceSystemNameID] FOREIGN KEY ([SourceSystemNameID]) REFERENCES [dbo].[trtBaseReference] ([idfsBaseReference]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_tstAggrSetting_tstCustomizationPackage__idfCustomizationPackage]...';


GO
ALTER TABLE [dbo].[tstAggrSetting] WITH NOCHECK
    ADD CONSTRAINT [FK_tstAggrSetting_tstCustomizationPackage__idfCustomizationPackage] FOREIGN KEY ([idfCustomizationPackage]) REFERENCES [dbo].[tstCustomizationPackage] ([idfCustomizationPackage]) NOT FOR REPLICATION;


GO
PRINT N'Creating Trigger [dbo].[TR_tstAggrSetting_A_Update]...';


GO

CREATE TRIGGER [dbo].[TR_tstAggrSetting_A_Update] ON [dbo].[tstAggrSetting]
FOR UPDATE
NOT FOR REPLICATION
AS
BEGIN

	IF (dbo.FN_GBL_TriggersWork() = 1 AND (UPDATE([idfsAggrCaseType]) OR UPDATE([idfCustomizationPackage])))  -- update to Primary Key is not allowed.
	BEGIN
		RAISERROR('Update Trigger: Not allowed to update PK.',16,1);
		ROLLBACK TRANSACTION;
	END

END
GO
PRINT N'Creating Trigger [dbo].[TR_tstAggrSetting_I_Delete]...';


GO


CREATE TRIGGER [dbo].[TR_tstAggrSetting_I_Delete] on [dbo].[tstAggrSetting]
INSTEAD OF DELETE
NOT FOR REPLICATION
AS
BEGIN

	IF (dbo.FN_GBL_TriggersWork() = 1)
	BEGIN

		WITH cteOnlyDeletedRecords([idfsAggrCaseType], [idfCustomizationPackage]) as
		(
			SELECT [idfsAggrCaseType], [idfCustomizationPackage] FROM deleted
			EXCEPT
			SELECT [idfsAggrCaseType], [idfCustomizationPackage] FROM inserted
		)

		UPDATE a
		SET  intRowStatus = 1
		FROM dbo.tstAggrSetting as a 
		INNER JOIN cteOnlyDeletedRecords as b 
			ON a.idfsAggrCaseType = b.idfsAggrCaseType
			AND a.idfCustomizationPackage = b.idfCustomizationPackage;

	END

END
GO
PRINT N'Refreshing Function [Report].[FN_AggregateSettings_GET]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[FN_AggregateSettings_GET]';


GO
PRINT N'Refreshing Function [dbo].[fnAggregateSettings]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[fnAggregateSettings]';


GO
PRINT N'Refreshing Function [Report].[FN_GBL_AggregateSettings_GET]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[FN_GBL_AggregateSettings_GET]';


GO
PRINT N'Creating Extended Property [dbo].[tstAggrSetting].[idfCustomizationPackage].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Country identifier', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tstAggrSetting', @level2type = N'COLUMN', @level2name = N'idfCustomizationPackage';


GO
PRINT N'Creating Extended Property [dbo].[tstAggrSetting].[strValue].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = 'Value', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tstAggrSetting', @level2type = N'COLUMN', @level2name = N'strValue';


GO
PRINT N'Refreshing Procedure [dbo].[USP_ADMIN_SITE_SET]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[USP_ADMIN_SITE_SET]';


GO
PRINT N'Refreshing Procedure [dbo].[USP_CONF_AggregateSetting_GetList]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[USP_CONF_AggregateSetting_GetList]';


GO
PRINT N'Refreshing Procedure [dbo].[USP_CONF_AggregateSetting_GetList_WithName]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[USP_CONF_AggregateSetting_GetList_WithName]';


GO
PRINT N'Refreshing Procedure [dbo].[USP_CONF_AggregateSetting_SET]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[USP_CONF_AggregateSetting_SET]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_MonthlyInfectiousDiseaseV6]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_MonthlyInfectiousDiseaseV6]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_MonthlyInfectiousDiseaseNew]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_MonthlyInfectiousDiseaseNew]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_AnnualInfectiousDisease]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_AnnualInfectiousDisease]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_VET_Form1ADiagnosticInvestigationsAZ]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_VET_Form1ADiagnosticInvestigationsAZ]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_VET_Form1ASanitaryMeasuresAZ]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_VET_Form1ASanitaryMeasuresAZ]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_VET_Form1AVaccinationMeasuresAZ]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_VET_Form1AVaccinationMeasuresAZ]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_VET_SummaryAggregateActionsAZ]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_VET_SummaryAggregateActionsAZ]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_Comparative_Calculations]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_Comparative_Calculations]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_ExternalComparative_Calculations]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_ExternalComparative_Calculations]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_MonthlyInfectiousDiseaseV61]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_MonthlyInfectiousDiseaseV61]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_ComparativeTwoYears_Calculations]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_ComparativeTwoYears_Calculations]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_BorderRayonsComparativeReport_Calculations]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_BorderRayonsComparativeReport_Calculations]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_Hum_ComparativeGG_Calculations]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_Hum_ComparativeGG_Calculations]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_ComparativeSeveralYearsByMonthsGG_Calculations]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_ComparativeSeveralYearsByMonthsGG_Calculations]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_MonthlyInfectiousDisease]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_MonthlyInfectiousDisease]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_MonthlyInfectiousDiseaseFatal]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_MonthlyInfectiousDiseaseFatal]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_FormN1InfectiousDiseases]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_FormN1InfectiousDiseases]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_FormN1InfectiousDiseases_IntrahospitalInfections]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_FormN1InfectiousDiseases_IntrahospitalInfections]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_CasesByRayonAndDiseaseSummary]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_CasesByRayonAndDiseaseSummary]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_Comparative]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_Comparative]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_ExternalComparative]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_ExternalComparative]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_ComparativeTwoYears]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_ComparativeTwoYears]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_ComparativeTwoYears_Graph]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_ComparativeTwoYears_Graph]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_Hum_ComparativeGG]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_Hum_ComparativeGG]';


GO
PRINT N'Refreshing Procedure [Report].[USP_REP_HUM_ComparativeSeveralYearsByMonthsGG]...';


GO
EXECUTE sp_refreshsqlmodule N'[Report].[USP_REP_HUM_ComparativeSeveralYearsByMonthsGG]';


GO
PRINT N'Checking existing data against newly created constraints';


GO
ALTER TABLE [dbo].[tstAggrSetting] WITH CHECK CHECK CONSTRAINT [FK_tstAggrSetting_tstSite_idfsSite];

ALTER TABLE [dbo].[tstAggrSetting] WITH CHECK CHECK CONSTRAINT [FK_tstAggrSetting_trtBaseReference__idfsAggrCaseType_R_941];

ALTER TABLE [dbo].[tstAggrSetting] WITH CHECK CHECK CONSTRAINT [FK_tstAggrSetting_trtBaseReference__idfsStatisticAreaType_R_1612];

ALTER TABLE [dbo].[tstAggrSetting] WITH CHECK CHECK CONSTRAINT [FK_tstAggrSetting_trtBaseReference__idfsStatisticPeriodType_R_1613];

ALTER TABLE [dbo].[tstAggrSetting] WITH CHECK CHECK CONSTRAINT [FK_tstAggrSetting_trtBaseReference_SourceSystemNameID];

ALTER TABLE [dbo].[tstAggrSetting] WITH CHECK CHECK CONSTRAINT [FK_tstAggrSetting_tstCustomizationPackage__idfCustomizationPackage];


GO
PRINT N'Update complete.';


GO
