// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using EIDSS.Localization.Models;

#nullable disable

namespace EIDSS.Localization.Contexts
{
    public partial class LocalizationContext : DbContext
    {
        public LocalizationContext()
        {
        }

        public LocalizationContext(DbContextOptions<LocalizationContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TrtResource> TrtResource { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Cyrillic_General_CI_AS");
            modelBuilder.Entity<USP_GBL_Languages_GETListResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<USP_GBL_Resource_GETListResult>().HasNoKey().ToView(null);

            modelBuilder.Entity<TrtResource>(entity =>
            {
                entity.HasKey(e => e.IdfsResource);

                entity.ToTable("trtResource");

                entity.Property(e => e.IdfsResource)
                    .ValueGeneratedNever()
                    .HasColumnName("idfsResource");

                entity.Property(e => e.AuditCreateDtm)
                    .HasColumnType("datetime")
                    .HasColumnName("AuditCreateDTM")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.AuditCreateUser)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasDefaultValueSql("(user_name())");

                entity.Property(e => e.AuditUpdateDtm)
                    .HasColumnType("datetime")
                    .HasColumnName("AuditUpdateDTM")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.AuditUpdateUser)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasDefaultValueSql("(user_name())");

                entity.Property(e => e.IdfsResourceType).HasColumnName("idfsResourceType");

                entity.Property(e => e.IntRowStatus).HasColumnName("intRowStatus");

                entity.Property(e => e.Rowguid)
                    .HasColumnName("rowguid")
                    .HasDefaultValueSql("(newid())");

                entity.Property(e => e.SourceSystemNameId).HasColumnName("SourceSystemNameID");

                entity.Property(e => e.StrMaintenanceFlag)
                    .HasMaxLength(20)
                    .HasColumnName("strMaintenanceFlag")
                    .HasDefaultValueSql("('Add')");

                entity.Property(e => e.StrReservedAttribute).HasColumnName("strReservedAttribute");

                entity.Property(e => e.StrResourceName)
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnName("strResourceName");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}